[package]
name = "Botfrag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.16.0"
serenity = "0.11"
reqwest = "0.11.16"
tokio = { version = "1.15", features = ["full"] }